---
title: "self-harm ideation plots"
author: "Helena Davies"
date: "18/05/2021"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment=NA,
                      prompt=FALSE,
                      cache=FALSE)
```

Delete everything in your global environment
```{r Delete everything in your global environment}
remove(list = ls())
```

#### Call in library script

```{r source files}
source("./libraries.R")
```

#### Call in functions script

```{r source files}
source("./functions.R")
```

#Retrieve the recent date
```{r Recent date}
date = Sys.Date()
date
```

# Read in data
```{r}
dat <- readRDS(file = "../data_cleaned/data.final.with.ED.groups2021-05-12.rds")
dim(dat)
colnames(dat)

#Drop one dup cohort name columns
dat$cohort_name.y <- NULL

dat <- dat %>% 
  rename(
    cohort_name = cohort_name.x
    )

```


##NEW experience of self-harm ideation; phases
```{r}

dat <- dat %>%
  mutate(new_selfharm_ideation_each_wave =
           case_when(
                     
                      taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     
                       (taf.have_you_contemplated_harming_yourself_.Wave_1a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_1a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_1a == "Yes") ~ 1,
                     
                     taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_1b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_1b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_1b == "Yes") ~ 2,
                     
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_2a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_2a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_2a == "Yes") ~ 3,
                     
                     taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_2b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_2b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_2b == "Yes") ~ 4,
                     
                     taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_3a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_3a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_3a == "Yes") ~ 5,
                     
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_3b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_3b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_3b == "Yes") ~ 6,
                     
                     taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_4a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_4a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_4a == "Yes") ~ 7,
                     
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_4b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_4b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_4b == "Yes") ~ 8,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_5a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_5a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_5a == "Yes") ~ 9,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_6b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_6b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_6b == "Yes") ~ 10,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_7a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_7a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_7a == "Yes") ~ 11,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_8b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_8b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_8b == "Yes") ~ 12,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_9a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_9a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_9a == "Yes") ~ 13,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_10b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_10b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_10b == "Yes") ~ 14,
                
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_11a == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_11a == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_11a == "Yes") ~ 15,
                    
                    taf.have_you_contemplated_harming_yourself_.Wavebaseline == "No" &
                     (taf.have_you_contemplated_harming_yourself_.Wave_12b == "Yes, once" |
                        taf.have_you_contemplated_harming_yourself_.Wave_12b == "Yes, more than once" |
                        taf.felt_weeks_past.1_.Wave_12b == "Yes") ~ 16
                     )
                     )
                     
        
        
#Check
dat %>%
  freq(new_selfharm_ideation_each_wave)


```

#Check number of people who answered question at each wave (use lifetime question as people only get shown 2 week question if YES to lifetime)
```{r}

#Phase 1a
phase1a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_1a)
         )
  
phase1a$ID.dup <- duplicated(phase1a$ID)

phase1a <- phase1a %>%
 filter(ID.dup == FALSE)

nrow(phase1a)


#Phase 1b
phase1b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_1b)
         )
  
phase1b$ID.dup <- duplicated(phase1b$ID)

phase1b <- phase1b %>%
 filter(ID.dup == FALSE)

nrow(phase1b)

#Phase 2a
phase2a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_2a)
         )

phase2a$ID.dup <- duplicated(phase2a$ID)

phase2a <- phase2a %>%
 filter(ID.dup == FALSE)

nrow(phase2a)


#Phase 2b
phase2b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_2b)
         )

phase2b$ID.dup <- duplicated(phase2b$ID)

phase2b <- phase2b %>%
 filter(ID.dup == FALSE)

nrow(phase2b)

#Phase 3a
phase3a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_3a)
         )

phase3a$ID.dup <- duplicated(phase3a$ID)

phase3a <- phase3a %>%
 filter(ID.dup == FALSE)

nrow(phase3a)

#Phase 3b
phase3b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_3b)
         )

phase3b$ID.dup <- duplicated(phase3b$ID)

phase3b <- phase3b %>%
 filter(ID.dup == FALSE)

nrow(phase3b)

#Phase 4a
phase4a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_4a)
         )

phase4a$ID.dup <- duplicated(phase4a$ID)

phase4a <- phase4a %>%
 filter(ID.dup == FALSE)

nrow(phase4a)

#Phase 4b
phase4b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_4b)
         )

phase4b$ID.dup <- duplicated(phase4b$ID)

phase4b <- phase4b %>%
 filter(ID.dup == FALSE)

nrow(phase4b)

#Phase 5a
phase5a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_5a)
         )

phase5a$ID.dup <- duplicated(phase5a$ID)

phase5a <- phase5a %>%
 filter(ID.dup == FALSE)

nrow(phase5a)

#Phase 6b
phase6b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_6b)
         )

phase6b$ID.dup <- duplicated(phase6b$ID)

phase6b <- phase6b %>%
 filter(ID.dup == FALSE)

nrow(phase6b)

#Phase 7a
phase7a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_7a)
         )

phase7a$ID.dup <- duplicated(phase7a$ID)

phase7a <- phase7a %>%
 filter(ID.dup == FALSE)

nrow(phase7a)


#Phase 8b
phase8b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_8b)
         )

phase8b$ID.dup <- duplicated(phase8b$ID)

phase8b <- phase8b %>%
 filter(ID.dup == FALSE)

nrow(phase8b)

#Phase 9a
phase9a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_9a)
         )

phase9a$ID.dup <- duplicated(phase9a$ID)

phase9a <- phase9a %>%
 filter(ID.dup == FALSE)

nrow(phase9a)

#Phase 10b
phase10b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_10b)
         )

phase10b$ID.dup <- duplicated(phase10b$ID)

phase10b <- phase10b %>%
 filter(ID.dup == FALSE)

nrow(phase10b)

#Phase 11a
phase11a <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_11a)
         )

phase11a$ID.dup <- duplicated(phase11a$ID)

phase11a <- phase11a %>%
 filter(ID.dup == FALSE)

nrow(phase11a)

#Phase 12b
phase12b <- dat %>%
  filter(!is.na(taf.have_you_contemplated_harming_yourself_.Wave_12b)
         )

phase12b$ID.dup <- duplicated(phase12b$ID)

phase12b <- phase12b %>%
 filter(ID.dup == FALSE)

nrow(phase12b)
```


