---
title: "COPING ED algorithms"
author: "Helena Davies"
date: "22/03/2021"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment=NA,
                      prompt=FALSE,
                      cache=FALSE)
```

Delete everything in your global environment
```{r Delete everything in your global environment}
remove(list = ls())
```

#### Call in library script

```{r source files}
source("./libraries.R")
```

#### Call in functions script

```{r source files}
source("./functions.R")
```

### Read in ED data: AN GLAD COPING
```{r}
dat.an.glad.coping <- readRDS(file = "../data_raw/diagnostics/an_coping_glad.rds")

# Inspect dimensions
dim(dat.an.glad.coping)
# Inspect colnames
colnames(dat.an.glad.coping)

nrow(dat.an.glad.coping)

```

### Select variables: GLAD AN
```{r glad select variables}

exclude_cols_dem <- c("ID",
                  "cohort_name")

dat.an.glad.coping.id <- dat.an.glad.coping %>% #new dataset with ID
  drop_na(externalDataReference) %>% # Drop NAs
  distinct(externalDataReference, .keep_all = TRUE) %>% 
  add_column(cohort_name = "coping_glad", .before = "an.1.lowest_weight_weigh_weighed") %>% #create new column 
  select(
         ID = externalDataReference,# ID
         cohort_name, # Sample
         an.1.lowest_weight_weigh_weighed,           
         an.1.what_was_the_illness.txt,                
         an.1.low_weight_time,                         
         an.1.low_weight_time.1,                        
         an.1.low_weight_time.2,                       
         an.1.how_old_were_you_then.txt,                
         an.1.how_tall_were_you_then,                  
         an.1.how_tall_were_you_then.1,                 
         an.1.how_tall_were_you_then.2,                
         an.1.feel_fat_low_weight,                      
         an.1.gain_weight_low_weight,                  
         an.1.anorexia_nervosa_low_weight,              
         an.1.anorexia_nervosa_low_weight.1,           
         an.1.not_at_all_dependentcompletely_dependent, 
         an.1.low_weight_health_negative,              
         an.1.body_larger_low_weight,                   
         an.1.started_time_periods,                    
         an.1.low_weight_periods_stop,                  
         an.1.roughly_periods_stopped.txt,             
         an.1.for_how_long_did_your_periods_stop,       
         an.1.for_how_long_did_your_periods_stop.1
         ) %>%
  add_numeric(., exclude = exclude_cols_dem) %>%
  mutate_if(is.numeric, ~na_if(., -88)) %>% # Recode missing values to NAs in numeric variables
  mutate_if(is.numeric, ~na_if(., -99)) %>%
  mutate_if(is.numeric, ~na_if(., -77)) %>%
  mutate_if(is.factor, ~na_if(., "Seen but not answered")) %>% # Recode missing values to NAs in factor variables
  mutate_if(is.factor, ~na_if(., "Don't know")) %>%
  mutate_if(is.factor, ~na_if(., "Prefer not to say")) %>%
  mutate_if(is.factor, ~na_if(., "Prefer not to answer")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Seen but not answered")) %>% # Drop empty factor levels
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Don't know")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Prefer not to answer")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Prefer not to say"))

# Inspect dimensions
dim(dat.an.glad.coping.id)
# Inspect colnames
colnames(dat.an.glad.coping.id)
#Differences
dim(dat.an.glad.coping)[1]-dim(dat.an.glad.coping.id)[1]


```

### Read in ED data: AN NBR COPING
```{r}
dat.an.nbr.coping <- readRDS(file = "../data_raw/diagnostics/an_coping_nbr.rds")

# Inspect dimensions
dim(dat.an.nbr.coping)
# Inspect colnames
colnames(dat.an.nbr.coping)

nrow(dat.an.nbr.coping)

```

### Select variables: GLAD AN
```{r glad select variables}

exclude_cols_dem <- c("ID",
                  "cohort_name")

dat.an.nbr.coping.id <- dat.an.nbr.coping %>% #new dataset with ID
  drop_na(subjectid) %>% # Drop NAs
  distinct(subjectid, .keep_all = TRUE) %>% 
  add_column(cohort_name = "coping_nbr", .before = "an.1.lowest_weight_weigh_weighed") %>% #create new column 
  select(
         ID = subjectid,# ID
         cohort_name, # Sample
         an.1.lowest_weight_weigh_weighed,           
         an.1.what_was_the_illness.txt,                
         an.1.low_weight_time,                         
         an.1.low_weight_time.1,                        
         an.1.low_weight_time.2,                       
         an.1.how_old_were_you_then.txt,                
         an.1.how_tall_were_you_then,                  
         an.1.how_tall_were_you_then.1,                 
         an.1.how_tall_were_you_then.2,                
         an.1.feel_fat_low_weight,                      
         an.1.gain_weight_low_weight,                  
         an.1.anorexia_nervosa_low_weight,              
         an.1.anorexia_nervosa_low_weight.1,           
         an.1.not_at_all_dependentcompletely_dependent, 
         an.1.low_weight_health_negative,              
         an.1.body_larger_low_weight = an.1.body_larger_people_thought, #Rename to same as GLAD               
         an.1.started_time_periods,                    
         an.1.low_weight_periods_stop = an.1.periods_stop_low_weight, #Rename to same as GLAD                   
         an.1.roughly_periods_stopped.txt,             
         an.1.for_how_long_did_your_periods_stop,       
         an.1.for_how_long_did_your_periods_stop.1
         ) %>%
  add_numeric(., exclude = exclude_cols_dem) %>%
  mutate_if(is.numeric, ~na_if(., -88)) %>% # Recode missing values to NAs in numeric variables
  mutate_if(is.numeric, ~na_if(., -99)) %>%
  mutate_if(is.numeric, ~na_if(., -77)) %>%
  mutate_if(is.factor, ~na_if(., "Seen but not answered")) %>% # Recode missing values to NAs in factor variables
  mutate_if(is.factor, ~na_if(., "Don't know")) %>%
  mutate_if(is.factor, ~na_if(., "Prefer not to say")) %>%
  mutate_if(is.factor, ~na_if(., "Prefer not to answer")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Seen but not answered")) %>% # Drop empty factor levels
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Don't know")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Prefer not to answer")) %>%
  mutate_if(is.factor, ~forcats::fct_drop(., only = "Prefer not to say"))

# Inspect dimensions
dim(dat.an.nbr.coping.id)
# Inspect colnames
colnames(dat.an.nbr.coping.id)
#Differences
dim(dat.an.nbr.coping)[1]-dim(dat.an.nbr.coping.id)[1]


```

##Merge data
```{r}
dat.an <- rbind(dat.an.nbr.coping.id,
                  dat.an.glad.coping.id)



##check columns
colnames(dat.an)

##check number of rows
nrow(dat.an)
```

