---
title: "Merging_EDBeh_SelfHarm"
author: "Helena Davies"
date: "27/01/2021"
output: html_document
---

#Set up
```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment=NA,
                      prompt=FALSE,
                      cache=FALSE)
options(bitmapType = 'quartz') # to render fonts better
```

Clear global environment
```{r Clear global environment}
remove(list = ls())
```

Retrieve the current date to use it for file endings to not overwrite files when one exports files
```{r Recent date}
date = Sys.Date()
```

Load packages
```{r}
library(tidyverse)
library(skimr)
```

# Import baseline data
```{r export data}
glad_baseline <- readRDS(file = "./data_cleaned/baseline_glad.rds")
dim(glad_baseline)

edgi_baseline <- readRDS(file = "./data_cleaned/baseline_edgi.rds")
dim(edgi_baseline)

nbr_baseline <- readRDS(file = "./data_cleaned/baseline_nbr.rds")
dim(nbr_baseline)

ramp_baseline <- readRDS(file = "./data_cleaned/baseline_ramp.rds")
dim(ramp_baseline)
```









glad/edgi data frame list
```{r glad/edgi data frame list}
dat <- bind_rows(
  glad,
  edgi,
  nbr,
  ramp
)
```



#Import follow up data
```{r}
edeq_coping <- readRDS(file = "./data_cleaned/baseline_glad.rds")
dim(glad_baseline)
```




```{r Skim data}
#look at the data
skimr::skim(dat)
```

```{r Save four cohorts as rds file}
saveRDS(object = dat, file = paste0(data_path, "/four_cohorts.rds"))
```